kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: observatory-reader
subjects:
  - kind: ServiceAccount
    name: observatory
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: observatory-reader
  apiGroup: rbac.authorization.k8s.io