kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: observatory-reader
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - endpoints
      - persistentvolumes
      - persistentvolumeclaims
      - replicationcontrollers
      - replicationcontrollers/scale
      - services
      - namespaces
      - events
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - list
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list