apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}
          restartPolicy: OnFailure
          containers:
          - name: {{ .Release.Name }}-cronjob
            image: verto.azurecr.io/observatory:master
            imagePullPolicy: Always
            env:
              - name: CLUSTER 
                value: verto-cluster
              - name: ELASTIC_APIKEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-runtime-secrets
                    key: elastic_apikey